# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
    - "5.5"

sudo: false

# WordPress version used in first build configuration.
env:
    - WP_VERSION=4.5.3

# Next we define our matrix of additional build configurations to test against.
# The versions listed above will automatically create our first configuration,
# so it doesn't need to be re-defined below.

# WP_VERSION specifies the tag to use. The way these tests are configured to run
# requires at least WordPress 3.8. Specify "master" to test against SVN trunk.

# Note that Travis CI supports listing these above to automatically build a
# matrix of configurations, but we're being nice here by manually building a
# total of four configurations even though we're testing 4 versions of PHP
# along with 2 versions of WordPress (which would build 8 configs otherwise).
# This takes half as long to run while still providing adequate coverage.

matrix:
  include:
    - php: "5.6"
      env: WP_VERSION=4.5.3
    - php: "7"
      env: WP_VERSION=4.5.3


# Clones WordPress and configures our testing environment.
before_script:
  - bash bin/install-wp-test.sh wordpress_test root '' localhost $WP_VERSION
script: phpunit
