# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
    - "5.4"

sudo: false

# WordPress version used in first build configuration.
env:
    - WP_VERSION=4.3

# Next we define our matrix of additional build configurations to test against.
# The versions listed above will automatically create our first configuration,
# so it doesn't need to be re-defined below.

# WP_VERSION specifies the tag to use. The way these tests are configured to run
# requires at least WordPress 3.8. Specify "master" to test against SVN trunk.

# Note that Travis CI supports listing these above to automatically build a
# matrix of configurations, but we're being nice here by manually building a
# total of four configurations even though we're testing 4 versions of PHP
# along with 2 versions of WordPress (which would build 8 configs otherwise).
# This takes half as long to run while still providing adequate coverage.

matrix:
  include:
    - php: "5.5"
      env: WP_VERSION=4.3
    - php: "5.6"
      env: WP_VERSION=4.3
    - php: "7"
      env: WP_VERSION=4.3


# Clones WordPress and configures our testing environment.
before_script:
    - export GIT_NAME=$(basename $(pwd))
    - export PLUGIN_SLUG="avh-em-permalinks"
    - git clone git://develop.git.wordpress.org/ /tmp/wordpress
    - cd ..
    - mkdir -p "/tmp/wordpress/src/wp-content/plugins/"
    - mv $GIT_NAME /tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG
    - cd /tmp/wordpress
    - git checkout $WP_VERSION
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - mysql -e "CREATE DATABASE rps_tests;" -uroot
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
# Comment out the echo as this interferes with Sessions.
    - sed -i '62 s/^/\/\/ /' tests/phpunit/includes/bootstrap.php
    - sed -i '34 s/^/\/\/ /' tests/phpunit/includes/install.php
# Setup database credentials
    - cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
script: phpunit
